In [3]:
import pandas as pd

covid_data = pd.read_csv('data/covid_data.csv', sep=',')
covid_data['date'] = pd.to_datetime(covid_data['date'])
covid_data['active'] = covid_data['confirmed'] - covid_data['deaths'] - covid_data['recovered']
covid_data = covid_data.sort_values(by=['country', 'date'])
covid_data['daily_confirmed'] = covid_data.groupby('country')['confirmed'].diff()
covid_data['daily_deaths'] = covid_data.groupby('country')['deaths'].diff()
covid_data['daily_recovered'] = covid_data.groupby('country')['recovered'].diff()
covid_data

,date,province/state,country,confirmed,deaths,recovered,active,daily_confirmed,daily_deaths,daily_recovered
2324,2020-02-24,NaN,Afghanistan,1.0,0.0,0.0,1.0,NaN,NaN,NaN
2419,2020-02-25,NaN,Afghanistan,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2522,2020-02-26,NaN,Afghanistan,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2628,2020-02-27,NaN,Afghanistan,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2738,2020-02-28,NaN,Afghanistan,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
5252,2020-03-12,NaN,occupied Palestinian territory,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5735,2020-03-14,NaN,occupied Palestinian territory,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5995,2020-03-15,NaN,occupied Palestinian territory,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6269,2020-03-16,NaN,occupied Palestinian territory,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6547,2020-03-17,NaN,occupied Palestinian territory,0.0,0.0,0.0,0.0,0.0,0.0,0.0